### ISSUE TITLE
NixCon 2024 venue proposal: Zürich, Switzerland 🇨🇭

### ISSUE THREAD

**Issue by ners** [nixcon/nixcon-proposals#4]
# Venue proposal

![](https://www.ost.ch/fileadmin/_processed_/8/6/csm_header_campus_rapperswil_bca53ef29c.jpg)

## Context

By virtue of being a neutral country in the heart of Europe, Switzerland is a prime location for an international meetup! Both flakers and non-flakers are welcome. :smile: 

Zürich has excellent connections. Getting to it from all over the world is easy, and there are many trains leading to the venue. We have [the best public transit system in Europe](https://www.bcg.com/publications/2017/transportation-travel-tourism-2017-european-railway-performance-index); day tickets cost at most 27 CHF.

There are many choices for accommodation, starting at as little as 70 CHF per night.

Have no fear of language barriers: Zürich is super international, so using English here is not a problem.

As this is a non-profit event, _the base tickets to this event would have to be free of charge_. We can offer a sponsor-tier ticket.

## Statistics

- Total capacity: 500
- Capacity in the main track room: 500
- A/V equipment in the track room: projector, speakers, streaming
- Hacking day capacity: many breakout rooms
- Number of tracks possible: 3
- Hallway track possible? yes
- Mini-conference (BoFs) tracks possible? yes, in many break-out rooms
- Distance (time) from an airport or train station in public transports: there is a train station right next to the venue. That train station is 55 min from airport, 37 min from main Zürich train station
- Average price for a hotel room in the city: sufficiently in advance, rooms can be found for as low as ~130 CHF/night in Rapperswil, ~100 CHF/night within 20 min of public transport; obviously there's no upper limit on price in hotels
- Potential costs to pay to the venue owner: 20,000 CHF
- Food: there is a large mensa, and food trucks can be deployed between the buildings

## Local team

**We host ZuriHac here every year**, as well as  NixOS ZHF hackathons every 6 months.

- Main organisers: @ners, @john-rodewald, @fmehta on behalf of OST
- Co-organisers: @infinisil, @chysi, @fricklerhandwerk, @das-g
- Zurich friends of Haskell team: @aherrmann, @jaspervdj
- too many amazing volunteers to list

### The main hall
![](https://zfoh.ch/images/zurihac.jpg)

![](https://www.ost.ch/fileadmin/_processed_/4/b/csm_zurihac2022_spj_81f112b066.jpg)

### The coffee lounge
![](https://serokell.io/files/ux/uxig9t54.IMG_20220613_124117_(1).jpg)

![](https://2017.zurihac.info/static/venue-3.55342459.jpg)

![](https://2017.zurihac.info/static/venue-4.7ed38953.jpg)

### Break-out rooms
![](https://2017.zurihac.info/static/venue-5.6c7f19fa.jpg)

### The reception area
![](https://2017.zurihac.info/static/venue-6.f4a64e16.jpg)

### The picnic area
![](https://jaspervdj.be/images/2019-09-03-zurihac-lake.jpg)

**Comment by gmile** [comment]
Zürich would be a fantastic place to hold the conference! I definitely endorse this proposal.

**Comment by infinisil** [comment]
Unfortunately plans changed, check https://discourse.nixos.org/t/nixcon-2024-preparation-meetings/41837/3

**Comment by ners** [comment]
Closing this as the Zürich proposal was unfortunately rejected.

**Comment by gmile** [comment]
@infinisil that is unfortunate, but thanks for update and a reference to the discourse! I'll keep my 🤞 for Berlin Nixconf to happen then
